#ifndef STUB_COMMON_DIALOG_H
#define STUB_COMMON_DIALOG_H
#define SCE_COMMON_DIALOG_STATUS_NONE 0
#define SCE_COMMON_DIALOG_STATUS_RUNNING 1
#define SCE_COMMON_DIALOG_STATUS_FINISHED 2
#define SCE_COMMON_DIALOG_MAGIC_NUMBER 0xC0D1A109
typedef unsigned int SceCommonDialogStatus;
#endif
